version: "3.9"
services:
  # db:
  #   image: postgres
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   env_file:
  #     - ./.env
  frontend:
    build: ./frontend
    command: yarn run dev
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    # depends_on:
    #   - backend
