# Generated by Django 3.2.16 on 2023-01-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_posts_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='posts_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='about_me',
            field=models.TextField(max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='post_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registration_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
