# Generated by Django 3.2.16 on 2023-01-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230110_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='post_number',
            new_name='number_of_posts',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
